import {
  getAllProducts,
  getAllProductsExtended,
  getProduct,
  createProduct,
  updateProduct,
  deleteProduct,
} from './ProductController';
import {
  getAllOptions,
  getOption,
  createOption,
  updateOption,
  deleteOption,
} from './OptionController';
import {
  getAllCategories,
  getAllCategoriesExtended,
  getCategory,
  createCategory,
  updateCategory,
  deleteCategory,
} from './CategoryController';
import {
  getAllCustomers,
  getCustomer,
  createCustomer,
  updateCustomer,
  deleteCustomer,
} from './CustomerController';
import {
  getAllOrders,
  getAllOrdersExtended,
  getOrder,
  createOrder,
  deleteOrder,
} from './OrderController';
import { getAllPayments, getPayment } from './PaymentController';
import {
  getAllEmployees,
  getEmployee,
  createEmployee,
  updateEmployee,
  deleteEmployee,
} from './EmployeeController';
import {
  getAllReviews,
  getAllReviewsForProduct,
  getReview,
  createReview,
  updateReview,
  deleteReview,
} from './ReviewController';

export {
  getAllProducts,
  getAllProductsExtended,
  getProduct,
  createProduct,
  updateProduct,
  deleteProduct,
  getAllOptions,
  getOption,
  createOption,
  updateOption,
  deleteOption,
  getAllCategories,
  getAllCategoriesExtended,
  getCategory,
  createCategory,
  updateCategory,
  deleteCategory,
  getAllCustomers,
  getCustomer,
  createCustomer,
  updateCustomer,
  deleteCustomer,
  getAllOrders,
  getAllOrdersExtended,
  getOrder,
  createOrder,
  deleteOrder,
  getAllPayments,
  getPayment,
  getAllEmployees,
  getEmployee,
  createEmployee,
  updateEmployee,
  deleteEmployee,
  getAllReviews,
  getAllReviewsForProduct,
  getReview,
  createReview,
  updateReview,
  deleteReview,
};
